name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the Docker images
      run: docker compose build

    - name: Start the Docker container
      run: docker compose up -d

    - name: Run Django Tests
      run: docker compose exec -T web python manage.py test

    - name: Stop containers
      if: always()
      run: docker compose down