# Generated by Django 5.2.13 on 2026-04-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Створено'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('received', 'Отримано')], default='created', max_length=20),
        ),
    ]
