# Generated by Django 5.2.13 on 2026-05-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_email_order_phone_alter_cart_id_and_more'),
        ('shop', '0008_subscriber'),
    ]

    operations = [
    ]
